INSERT INTO DENTISTS VALUES (1, 'Helgi', 'Hambavalu');

INSERT INTO DENTISTS VALUES (2, 'Kalle', 'Kaaries');

INSERT INTO DENTISTS VALUES (3, 'Pärtel', 'Puur');

INSERT INTO DENTIST_VISIT VALUES (1, 2, 'Kalle Kaaries', '2021-05-09');

INSERT INTO DENTIST_VISIT VALUES (2, 2, 'Kalle Kaaries', '2021-05-10');

INSERT INTO DENTIST_VISIT VALUES (3, 1, 'Helgi Hambavalu', '2021-06-13');

INSERT INTO DENTIST_VISIT VALUES (4, 3, 'Pärtel Puur', '2021-05-17');